apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: template-build-pipelinerun
spec:
  pipelineRef:
    name: template-build
  params:
  - name: git-url
    value: ""
  - name: revision
    value: ""
  - name: output-image
    value: ""
  - name: path-context
    value: .
  - name: dockerfile
    value: Dockerfile
  - name: rebuild
    value: "false"
  - name: skip-checks
    value: "false"
  - name: hermetic
    value: "false"
  - name: prefetch-input
    value: ""
  - name: java
    value: "false"
  - name: snyk-secret
    value: ""
  # - name: deployment-name
  #   value: pipelines-vote-api
  # - name: git-url
  #   value: https://github.com/openshift/pipelines-vote-api.git
  # - name: IMAGE
  #   value: image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/pipelines-vote-api
  workspaces:
  - name: shared-workspace
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 500Mi